mode: train

data:
  category: "pair"
  data_path: {"train":"./data/new_train_2class_v7/", "val":"./data/new_train_2class_val/"} 
  dataloader:
    train:
      dataloader_params:
        batch_size: 1
        pin_memory: True
        num_workers: 16

  preprocess:
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["IM"]
        dimension_order_out: "CYX"
        T: 0
        Z: 0
    - module_name: monai.transforms
      func_name: LoadImaged
      params:
        keys: ["GT"]
        dtype: int
        dimension_order_out: "YX"
        C: 0
        T: 0
        Z: 0
    - module_name: monai.transforms
      func_name: AddChanneld
      params:
        keys: ["GT"]
    - module_name: monai.transforms
      func_name: NormalizeIntensityd
      params:
        channel_wise: True
        keys: ["IM"]
    # - module_name: monai.transforms
    #   func_name: RandSpatialCropSamplesd
    #   params:
    #     keys: ["IM", "GT"]
    #     random_size: False
    #     num_samples: 1
    #     roi_size: [512, 512]
    - module_name: monai.transforms
      func_name: EnsureTyped
      params:
        keys: ["IM", "GT"]
  augmentation:
    - module_name: monai.transforms
      func_name: RandFlipd
      params:
        prob: 0.5
        keys: ["IM", "GT"]
    - module_name: monai.transforms
      func_name: RandHistogramShiftd
      params:
        prob: 0.25
        num_control_points: 50
        keys: ["IM"]
    - module_name: monai.transforms
      func_name: Rand2DElasticd
      params:
        prob: 0.25
        spacing: [32, 32]
        magnitude_range: [1, 5]
        rotate_range: [0, 0.5]
        scale_range: [0.1, 0.25]
        translate_range: [10, 50]
        padding_mode: "reflection"
        mode: "nearest"
        keys: ["IM", "GT"]

model:
  framework: FCN
  model_extra:
    pre-train: ./lightning_logs/version_24/checkpoints/last.ckpt
  net:
    # module_name: monai.networks.nets
    # func_name: HighResNet
    # params:
    #   in_channels: 1
    #   out_channels: 2
    #   spatial_dims: 2
    module_name: monai.networks.nets
    func_name: AttentionUnet
    params:
      in_channels: 2
      out_channels: 3
      spatial_dims: 2
      channels: [32, 64, 128, 256, 512]
      strides: [2, 2, 2, 2, 2]
      dropout: 0.2
  criterion:
    module_name: monai.losses
    func_name: GeneralizedDiceFocalLoss
    params:
      softmax: True
      to_onehot_y: True
      focal_weight: [1, 1, 5]
  optimizer:
    module_name: torch.optim
    func_name: AdamW
    params:
      lr: 0.0001
      weight_decay: 0.0005
  scheduler:
    module_name: torch.optim.lr_scheduler
    func_name: ExponentialLR
    params:
      gamma: 0.97
trainer:
  verbose: True
  params:
    gpus: 1
    precision: 16
    max_epochs: 3000
    detect_anomaly: True
  callbacks:
    # - module_name: pytorch_lightning.callbacks.early_stopping
    #   func_name: EarlyStopping
    #   params:
    #     monitor: 'val_loss'
    #     patience: 50 
    #     verbose: True
    - module_name: pytorch_lightning.callbacks.model_checkpoint
      func_name: ModelCheckpoint
      params:
        monitor: 'val_loss'
        filename: '{epoch}-{val_loss:.5f}'
        save_top_k: 5
        save_last: True
        save_weights_only: True 